name: Deploy to cPanel on Commit

on:
  push:
    branches:
      - main  # Trigger deployment on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Choose Deployment Method
        uses: actions/checkout@v3
        with:
          persist-credentials: autos # Optional: Save deployment method credential for future runs
        env:
          # Replace placeholders with your actual values
          CPANEL_HOST: 198.37.120.210
          CPANEL_USERNAME: kayblez2
          DEPLOYMENT_METHOD: cpanel-api

      - if: env.DEPLOYMENT_METHOD == 'cpanel-api'
        uses: 1Password/action@v1
        with:
          entry: 859S00HNG5JK4WF3MGRSDPXLRHD45VLE  # Store token securely in 1Password
        env:
          CPANEL_API_TOKEN: ${{ steps.onepassword.outputs.password }}

      - if: env.DEPLOYMENT_METHOD == 'ftp-ssh'
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Store key securely in GitHub Secrets

      - name: Deploy with chosen method
        run: |
          if [[ "${{ env.DEPLOYMENT_METHOD }}" == "cpanel-api" ]]; then
            # Use cPanel API commands here (refer to cPanel API documentation)
            curl -X POST https://CPANEL_HOST/cpsapi/update.uphp -d user=CPANEL_USERNAME -d api_key=${1Password} -d module=FileMan -d action=update -d newfile='{"path":"/path/to/your/file","content":"NEW_CONTENT"}'
          else
            # Use SCP over SSH commands here (e.g., scp -i ~/.ssh/id_rsa ./ user@${{ env.CPANEL_HOST }}:/path/to/site)
          fi

